### ISSUE TITLE
2.0.0 Roadmap

### ISSUE THREAD

**Issue by UberPilot** [ShatteredSuite/ShatteredScrolls2#1]
This is the master issue for 2.0.0. When this is done, we're very close to release.
## Implement
- [x] Interact Events for Scrolls
- [ ] GUIs
  - [ ] Warps
    - [ ] Warp List
    - [ ] Warp Detail (rename, relocate, delete, warp to)
  - [ ] Scrolls
    - [ ] Scroll List
    - [ ] Scroll Detail (rename, relore, set default, change default binding, change crafting?)
- [x] Commands
  - [x] Warps (rename, relocate, delete, warp to)
  - [x] Scrolls (give, get, create, delete, rename, relore, set default, change default binding)

## Test
- [x] Configuration Reading
- [x] Item Loading/Detection
- [x] Conversion from v1
- [ ] API -- Perhaps move GUI to another plugin?

## Possible 
- [ ] Scroll Books 
  - [ ] Interact Events
  - [ ] GUI
  - [ ] Data Storage + Manipulation (Copy NBT from the member scrolls?)
